import { Platform, StyleSheet } from "react-native";

import type { AppColors } from "./palettes";

export function createShellStyles(c: AppColors) {
  return StyleSheet.create({
    flex: { flex: 1 },
    scroll: {
      paddingHorizontal: 24,
      paddingTop: 12,
      paddingBottom: 40,
      gap: 12,
      flexGrow: 1,
    },
    eyebrow: {
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 2.2,
      textTransform: "uppercase",
      color: c.textMuted,
      marginBottom: 4,
    },
    screenTitle: {
      fontSize: 26,
      fontWeight: "800",
      letterSpacing: -0.5,
      color: c.textPrimary,
    },
    screenSubtitle: {
      fontSize: 17,
      fontWeight: "600",
      color: c.textSecondary,
      marginTop: 6,
    },
    mutedLine: {
      fontSize: 14,
      color: c.textMuted,
      marginBottom: 4,
    },
    glassCard: {
      borderRadius: 20,
      padding: 20,
      backgroundColor: c.glass,
      borderWidth: 1,
      borderColor: c.glassBorder,
      marginTop: 8,
    },
    cardTitle: {
      fontSize: 12,
      fontWeight: "700",
      color: c.textSecondary,
      marginBottom: 14,
      textTransform: "uppercase",
      letterSpacing: 1.2,
    },
    section: {
      fontSize: 11,
      fontWeight: "700",
      color: c.textMuted,
      marginTop: 18,
      marginBottom: 4,
      textTransform: "uppercase",
      letterSpacing: 2,
    },
    statsRow: { flexDirection: "row", gap: 20 },
    stat: { flex: 1, alignItems: "center" },
    statValue: { fontSize: 28, fontWeight: "800", color: c.textPrimary },
    statLabel: { fontSize: 13, color: c.textMuted, marginTop: 6 },
    primaryBtn: {
      borderRadius: 14,
      backgroundColor: c.accent,
      alignItems: "center",
      paddingVertical: 15,
    },
    primaryBtnDisabled: { opacity: 0.55 },
    primaryBtnText: {
      color: "#FFF",
      fontSize: 16,
      fontWeight: "700",
    },
    outlineBtn: {
      borderRadius: 14,
      backgroundColor: c.glass,
      borderWidth: 1,
      borderColor: c.inputBorderFocus,
      alignItems: "center",
      paddingVertical: 15,
    },
    outlineBtnText: {
      color: c.accentSoft,
      fontSize: 16,
      fontWeight: "700",
    },
    signOutBtn: {
      marginTop: 20,
      backgroundColor: c.pillBg,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: c.glassBorder,
      alignItems: "center",
      paddingVertical: 14,
    },
    signOutText: {
      color: c.textSecondary,
      fontSize: 16,
      fontWeight: "600",
    },
    backBtn: { alignSelf: "flex-start", marginBottom: 8, paddingVertical: 4 },
    backText: { color: c.accentSoft, fontWeight: "600", fontSize: 16 },
    header: {
      paddingHorizontal: 20,
      paddingTop: 4,
      paddingBottom: 10,
      backgroundColor: "transparent",
      borderBottomWidth: 0,
    },
    headerTitle: { fontSize: 22, fontWeight: "800", color: c.textPrimary },
    label: {
      fontSize: 13,
      fontWeight: "600",
      color: c.textSecondary,
      marginBottom: 8,
      marginLeft: 2,
    },
    input: {
      backgroundColor: c.inputBg,
      borderWidth: 1,
      borderColor: c.inputBorder,
      borderRadius: 14,
      paddingHorizontal: 16,
      paddingVertical: Platform.OS === "ios" ? 16 : 14,
      fontSize: 16,
      color: c.textPrimary,
      fontWeight: "500",
    },
    chip: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 20,
      backgroundColor: c.pillBg,
      borderWidth: 1,
      borderColor: c.glassBorder,
    },
    chipActive: {
      backgroundColor: c.chipActiveBg,
      borderColor: c.inputBorderFocus,
    },
    chipText: { color: c.textMuted, fontWeight: "600", fontSize: 13 },
    chipTextActive: { color: c.textPrimary },
    formBlock: { paddingHorizontal: 20, paddingVertical: 12, gap: 10 },
    listContent: { paddingHorizontal: 20, paddingBottom: 24, paddingTop: 8 },
    row: {
      backgroundColor: c.glass,
      borderRadius: 14,
      padding: 16,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: c.glassBorder,
    },
    rowTitle: { fontSize: 16, fontWeight: "600", color: c.textPrimary },
    rowMeta: { fontSize: 13, color: c.textMuted, marginTop: 4 },
    empty: { color: c.textMuted, textAlign: "center", marginTop: 20 },
    tokenBox: {
      fontSize: 14,
      fontFamily: Platform.select({
        ios: "Menlo",
        android: "monospace",
        default: "monospace",
      }),
      backgroundColor: c.inputBg,
      padding: 14,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: c.inputBorder,
      color: c.textPrimary,
    },
    meta: { fontSize: 13, color: c.textMuted },
    centeredBlock: {
      flex: 1,
      justifyContent: "center",
      paddingHorizontal: 24,
      gap: 12,
    },
    ghostBtn: { alignItems: "center", paddingVertical: 12 },
    ghostText: { color: c.accentSoft, fontWeight: "600", fontSize: 15 },
    secondarySolidBtn: {
      borderRadius: 14,
      backgroundColor: c.pillBg,
      borderWidth: 1,
      borderColor: c.glassBorder,
      alignItems: "center",
      paddingVertical: 15,
    },
    secondarySolidBtnText: {
      color: c.textPrimary,
      fontSize: 16,
      fontWeight: "700",
    },
    hint: {
      fontSize: 12,
      color: c.textMuted,
      lineHeight: 17,
      marginTop: 4,
    },
    linkText: { color: c.accentSoft, fontWeight: "700", fontSize: 15 },
    linkBtn: { marginTop: 10, alignSelf: "flex-start" },
    secondaryPickerBtn: {
      marginTop: 8,
      borderRadius: 14,
      backgroundColor: c.glass,
      borderWidth: 1,
      borderColor: c.inputBorderFocus,
      alignItems: "center",
      paddingVertical: 14,
    },
    secondaryPickerBtnText: {
      color: c.accentSoft,
      fontSize: 16,
      fontWeight: "700",
    },
  });
}
